# This file is generated by Nx and modified for multi-service support.
#
# Build the docker image with `npx nx docker-build api-gateway` or `npx nx docker-build products`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t <service-name>`.
ARG APP_NAME=products

FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

# Create user and group
RUN addgroup --system nestjs && \
          adduser --system -G nestjs nestjs

# Copy built application based on APP_NAME argument
ARG APP_NAME
COPY dist/apps/${APP_NAME} ./app/
COPY proto ./proto/

# Copy package.json and install production dependencies
COPY package.json ./
RUN npm install --omit=dev --silent

# Change ownership to nestjs user
RUN chown -R nestjs:nestjs .

# Switch to non-root user
USER nestjs

CMD [ "node", "app" ]
