apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nestjs-microservices.fullname" . }}-proto
  labels:
    {{- include "nestjs-microservices.labels" . | nindent 4 }}
data:
  products.proto: |
    syntax = "proto3";

    package products;

    service ProductService {
        rpc getProduct (ProductRequest) returns (ProductResponse);
    }

    message ProductRequest {
        int32 productId  = 1;
    }

    message ProductResponse {
        int32 productId = 1;
        string name = 2;
        int32 price = 3;
    }
