{{- if .Values.products.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nestjs-microservices.fullname" . }}-products
  labels:
    {{- include "nestjs-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: products
spec:
  replicas: {{ .Values.products.replicaCount }}
  selector:
    matchLabels:
      {{- include "nestjs-microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: products
  template:
    metadata:
      labels:
        {{- include "nestjs-microservices.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: products
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: products
          image: "{{ .Values.image.registry }}{{ .Values.image.repository }}/products:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.products.service.grpcPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.products.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: proto-files
              mountPath: /app/proto
              readOnly: true
          resources:
            {{- toYaml .Values.products.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: proto-files
          configMap:
            name: {{ include "nestjs-microservices.fullname" . }}-proto
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
